### ISSUE TITLE
User is unauthorized

### ISSUE THREAD

**Issue by dmitry-js** [SP-l33t/Dogiators-Telethon#1]
After authorization and creation of a new session, all sessions in telegram are terminated and the account is logged out from all devices.

The script fails with the error:
```
2024-10-01 23:23:10 | INFO | me_telethon | Bot will start in 2s
2024-10-01 23:23:13 | INFO | me_telethon | Running Proxy-less
2024-10-01 23:23:29 | ERROR | me_telethon | Invalid Session: me_telethon: User is unauthorized
```

This is probably telethon issue

**Comment by SP-l33t** [comment]
Unfurtonately, it started to hit me too, recently. (2 of the most recent accs got baned by TG)

It never happened to me before until the 3 days ago. There is only one possible change that could've affected it. If it wasn't the case, then I don't have any other ideas. I will try to rollback some of the recent changes to see if it was the case.

**Comment by dmitry-js** [comment]
I guess Pyrogram is still a stable solution, I never had any problems with it

**Comment by SP-l33t** [comment]
Unfortunately, fix isn't gonna do anything.
Wanted to rollback similar change (https://github.com/SP-l33t/Bool_Bot-Telethon/commit/7911f9e42456988d8ebf74f9cf39b73498a5524e)

But sadly,  
`client.get_input_entity`
and
`client(contacts.ResolveUsernameRequest`
are literally the same. get_input_entity uses cached info and if none is found, uses ResolveUsernameRequest.

**Comment by SP-l33t** [comment]
> OK, thanks. If that doesn't help, maybe it makes sense to try Pyrogram, I've never had any problems with it before

Now works with both, pyrogram and telethon .sessions
