### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by 9OsnoVa** [SP-l33t/Dogiators-Telethon#10]
![image](https://github.com/user-attachments/assets/1ab3a9fd-38f8-4c15-ba1e-9d65d815561c)

**Comment by SP-l33t** [comment]
They updated their API a few days ago and I didn't have enough time to fix it yet. Hopefully this weekend

**Comment by SP-l33t** [comment]
Updated the bot. Should work fine now

**Comment by 9OsnoVa** [comment]
thx
