### ISSUE TITLE
Main JS updated. New file name: '/assets/index-CLJmddfa.js'

### ISSUE THREAD

**Issue by vstri** [SP-l33t/Dogiators-Telethon#13]
![image](https://github.com/user-attachments/assets/bb73e6a3-8335-4c3f-bd3b-d811e1f7a986)

**Comment by SP-l33t** [comment]
Updated the signature

**Comment by vstri** [comment]
the same issue
![image](https://github.com/user-attachments/assets/73812521-6ee8-4c0b-8cc0-22ad33b6e3b5)
