### ISSUE TITLE
 Main JS updated. New file name: '/assets/index-Up4rMdoT.js'.

### ISSUE THREAD

**Issue by vstri** [SP-l33t/Dogiators-Telethon#14]
![image](https://github.com/user-attachments/assets/0a4d73da-5097-49a8-847e-2c94480b1c57)

**Comment by damondiamond** [comment]
same

**Comment by SP-l33t** [comment]
It's not an issue. It's just a protection, which can be disabled with .evn
Updated bot signatures.
