### ISSUE TITLE
error

### ISSUE THREAD

**Issue by damondiamond** [SP-l33t/Dogiators-Telethon#2]
CHECK accounts_config.json as it might be corrupted

how to fix it?

**Comment by SP-l33t** [comment]
Can you send a picture of accounts_config.json with masked api_id, api_hash and proxy?
Or leave your TG username here and I will reach you.

**Comment by damondiamond** [comment]
> Can you send a picture of accounts_config.json with masked api_id, api_hash and proxy? Or leave your TG username here and I will reach you.

![sfsdfs](https://github.com/user-attachments/assets/17526931-c9e9-4265-b025-7c089a309341)
data changed

**Comment by SP-l33t** [comment]
Fixed in
https://github.com/SP-l33t/Dogiators-Telethon/commit/c2846d76802356931400d3d52679c27ff46f65a3
You dont need to delete accounts_config.json. Just update and run.
