### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by beetlejuicerus** [SP-l33t/Dogiators-Telethon#5]
Добрый день! Выдает такую ошибку, в чем может быть проблема?

<img width="561" alt="Снимок экрана 2024-10-07 в 17 53 55" src="https://github.com/user-attachments/assets/f0d2120b-39c2-4774-87df-2c7d179e917f">

**Comment by SP-l33t** [comment]
Добрый вечер!
Перед запуском, необходимо установить зависимости из requirements.txt
