### ISSUE TITLE
used warmed up account but got ban

### ISSUE THREAD

**Issue by onemorer0ad** [SP-l33t/Dogiators-Telethon#8]
luckilu didn't use it on much accs just 2 of them
Any tips to make it safe? maybe add delay to upgrade card or can it be by using bad api id api hash?

**Comment by SP-l33t** [comment]
Did you get banned by telegram, or by Dogiators bot?

**Comment by onemorer0ad** [comment]
By tg

**Comment by SP-l33t** [comment]
Upgrading cards doesn't interract with Telegram. You got banned during other actions, and sadly, there isn't much I can do.

You can try using pyrogram if you want. I added support for pyrogram .session files in the latest update.

It might be caused by api_id you use, but nobody knows the exact reason.

**Comment by SP-l33t** [comment]
No, telethon and pyrogram are 2 completely different libs and have different formats.

**Comment by onemorer0ad** [comment]
so you mean to rewrite your software on pyrogram or it already can works with?

**Comment by SP-l33t** [comment]
My software works with both. You can just put pyrogram session file in one of the following directories
/sessions
/sessions/pyrogram
And my script withh automatically check if its pyrogram or telethon and use the suitable lib

**Comment by onemorer0ad** [comment]
2024-10-20 22:42:05 | SUCCESS | Successfully connected to proxy. IP: 
2024-10-20 22:42:05 | INFO | +12345 | Bot will start in 25s
2024-10-20 22:42:32 | INFO | +12345 | Proxy IP: 
2024-10-20 22:42:50 | ERROR | +12345 | Invalid Session: +12345: User is unauthorized

Через пирограм почему то пишет не авторизован, хотя сессия живая( бан тг не дал)

**Comment by SP-l33t** [comment]
Проверил на нескольких сессиях pyrogram, подобную проблему воспроизвести не удалось
