### ISSUE TITLE
Requirements install error

### ISSUE THREAD

**Issue by thund3rbreath** [SP-l33t/Dogiators-Telethon#9]
![Uploading Screenshot_20241026_032533_com_termux_TermuxActivity.jpg…]()

**Comment by SP-l33t** [comment]
Can you provide some details?

**Comment by thund3rbreath** [comment]
![Screenshot_20241026_032541_com_termux_TermuxActivity](https://github.com/user-attachments/assets/bd52d30f-1a22-4842-9815-c016df9dca6d)

**Comment by thund3rbreath** [comment]
![Screenshot_20241026_032533_com_termux_TermuxActivity](https://github.com/user-attachments/assets/c9715796-f3f6-4050-9004-f20b9fb200ac)

**Comment by SP-l33t** [comment]
It's not my script's failure, but termux fails to install PyQT5. I tried to look for a solution, but didn't find a working one.

**Comment by SP-l33t** [comment]
Actually found a way. You can install PyQT5 with
`pgk install PyQT5`
Then you need to copy it from python3.12 to python3.10
`find /data/data/com.termux/files/usr/lib/python* -type d \( -name "PyQt5*" -o -name "pyqt5*" \) -print0 | xargs -0 -I {} cp -r {} /data/data/com.termux/files/usr/lib/python3.10/site-packages/`

Then you can just run
`pip3.10 install -r requirements`

**Comment by thund3rbreath** [comment]
Thanks after this pyqt is installed, but it cant run the script..
Segmentation error
![Screenshot_20241107_234329_com_termux_TermuxActivity](https://github.com/user-attachments/assets/2ed03229-9bff-4768-a847-8f46ecedc712)

**Comment by ivan52605** [comment]
А можно просто юзать нормальный терминал

**Comment by SP-l33t** [comment]
> Thanks after this pyqt is installed, but it cant run the script.. Segmentation error ![Screenshot_20241107_234329_com_termux_TermuxActivity](https://private-user-images.githubusercontent.com/185608892/384078903-2ed03229-9bff-4768-a847-8f46ecedc712.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDg5MjYsIm5iZiI6MTczMTM0ODYyNiwicGF0aCI6Ii8xODU2MDg4OTIvMzg0MDc4OTAzLTJlZDAzMjI5LTliZmYtNDc2OC1hODQ3LThmNDZlY2VkYzcxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxODEwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTQ5ZmQxMTg4ZDQ0ZmUwYmRiN2UwZGJmMGU4YjY3YzQ2MDNmNDlmOGVkNjM1ZTE4YWQwNjNiM2ZmY2IwNDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2zl5gnHEPOGAxh-lmrFz_HgteIGN0NaiMwAPdFBa1W8)

I think I finally found a solution to this issue. I will try to add support for python3.12 soon.

**Comment by SP-l33t** [comment]
> Thanks after this pyqt is installed, but it cant run the script.. Segmentation error ![Screenshot_20241107_234329_com_termux_TermuxActivity](https://private-user-images.githubusercontent.com/185608892/384078903-2ed03229-9bff-4768-a847-8f46ecedc712.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3Njg0MjQsIm5iZiI6MTczMTc2ODEyNCwicGF0aCI6Ii8xODU2MDg4OTIvMzg0MDc4OTAzLTJlZDAzMjI5LTliZmYtNDc2OC1hODQ3LThmNDZlY2VkYzcxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNDQyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTFlMzNlZWM1YTNkMGNiMDZkMTVjODA1ZjFlMDg0ZWVmNzBhMzU3ZjAyNDY0NzM2NDBiMzQ4NmNiZmQ2NDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.urbxhTrGsfZirhclbrN4JoLtbSAai45Kl8MA0zIdmTw)

Ok, so for now forget about python3.10 😀
Now try to run
`pip install --force-reinstall git+https://github.com/felixonmars/Js2Py@fd7df4a91fb08060914c7b1d9e94583d18f3371b
`
and then run the script.
